# Generated by Django 4.2.8 on 2026-04-10 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanHanh',
            fields=[
                ('ban_hanh_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_ban_hanh', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BanHanh',
            },
        ),
        migrations.CreateModel(
            name='ChiNhanh',
            fields=[
                ('chi_nhanh_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_chi_nhanh', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ChiNhanh',
            },
        ),
        migrations.CreateModel(
            name='ChuyenTiep',
            fields=[
                ('chuyen_tiep_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_chuyen_tiep', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ChuyenTiep',
            },
        ),
        migrations.CreateModel(
            name='CongViec',
            fields=[
                ('cong_viec_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_cong_viec', models.CharField(max_length=255)),
                ('noi_dung_cong_viec', models.TextField()),
                ('nguon_giao', models.CharField(blank=True, choices=[('Văn Bản đi', 'Văn Bản đi'), ('Văn Bản Đến', 'Văn Bản Đến')], max_length=255, null=True)),
                ('trang_thai', models.CharField(max_length=255)),
                ('ngay_bat_dau', models.DateField()),
                ('han_xu_ly', models.DateTimeField()),
                ('ngay_cap_nhat_giao_viec', models.DateField(default=django.utils.timezone.now)),
                ('ket_qua_xu_ly', models.TextField(blank=True, null=True)),
                ('ngay_xu_ly', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'CongViec',
            },
        ),
        migrations.CreateModel(
            name='DonViNgoai',
            fields=[
                ('don_vi_ngoai_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_don_vi', models.CharField(max_length=255)),
                ('dia_chi', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'DonViNgoai',
            },
        ),
        migrations.CreateModel(
            name='HoSoVanBan',
            fields=[
                ('ho_so_van_ban_id', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de_ho_so', models.CharField(max_length=255)),
                ('ky_hieu_ho_so', models.CharField(max_length=255, unique=True)),
                ('ngay_tao_ho_so', models.DateField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateField(default=django.utils.timezone.now)),
                ('thoi_gian_bao_quan', models.CharField(choices=[('Theo quy định - 2 năm', 'Theo quy định - 2 năm'), ('Theo quy định - 5 năm', 'Theo quy định - 5 năm'), ('Theo quy định - 10 năm', 'Theo quy định - 10 năm'), ('Vĩnh viễn', 'Vĩnh viễn')], max_length=255)),
                ('so_nam_luu_tru', models.PositiveIntegerField()),
                ('trang_thai', models.IntegerField(choices=[(1, 'Hiện hành'), (2, 'Lưu trữ')])),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HoSoVanBan',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('nguoi_dung_id', models.AutoField(primary_key=True, serialize=False)),
                ('ho_va_ten', models.CharField(max_length=255)),
                ('chuc_vu', models.CharField(choices=[('Lãnh Đạo', 'Lãnh Đạo'), ('Chuyên Viên', 'Chuyên Viên'), ('Văn Thư', 'Văn Thư')], max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sdt', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'NguoiDung',
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('phong_ban_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_phong_ban', models.CharField(max_length=255)),
                ('chi_nhanh', models.ForeignKey(db_column='chi_nhanh_id', on_delete=django.db.models.deletion.CASCADE, to='core.chinhanh')),
                ('truong_phong', models.ForeignKey(blank=True, db_column='truong_phong_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nguoidung')),
            ],
            options={
                'db_table': 'PhongBan',
            },
        ),
        migrations.CreateModel(
            name='VanBan',
            fields=[
                ('van_ban_id', models.AutoField(primary_key=True, serialize=False)),
                ('so_ky_hieu', models.CharField(max_length=255)),
                ('trich_yeu', models.CharField(max_length=255)),
                ('hinh_thuc', models.TextField(choices=[('Công văn', 'Công văn'), ('Quyết định', 'Quyết định'), ('Thông báo', 'Thông báo'), ('Báo cáo', 'Báo cáo'), ('Hợp đồng', 'Hợp đồng'), ('Quy chế', 'Quy chế'), ('Kế hoạch', 'Kế hoạch'), ('Chỉ thị', 'Chỉ thị'), ('Nghị quyết', 'Nghị quyết'), ('Giấy mời', 'Giấy mời'), ('Phiếu trình', 'Phiếu trình')])),
                ('loai_van_ban', models.CharField(choices=[('Văn bản điều hành', 'Văn bản điều hành'), ('Văn bản tài chính', 'Văn bản tài chính'), ('Văn bản pháp lý', 'Văn bản pháp lý'), ('Văn bản nhân sự', 'Văn bản nhân sự'), ('Báo cáo tài chính', 'Báo cáo tài chính'), ('Hồ sơ kê khai thuế', 'Hồ sơ kê khai thuế'), ('Văn bản kế hoạch', 'Văn bản kế hoạch'), ('Văn bản dự án', 'Văn bản dự án'), ('Báo cáo tiến độ', 'Báo cáo tiến độ')], max_length=255)),
                ('don_vi_ban_hanh', models.CharField(max_length=255)),
                ('don_vi_soan_thao', models.CharField(max_length=255)),
                ('ngay_van_ban', models.DateField(auto_now_add=True)),
                ('ngay_den', models.DateField()),
                ('han_xu_ly', models.DateField(blank=True, null=True)),
                ('ngay_cap_nhat', models.DateField(default=django.utils.timezone.now)),
                ('do_khan', models.CharField(blank=True, choices=[('Hỏa tốc', 'Hỏa tốc'), ('Khẩn', 'Khẩn'), ('Bình thường', 'Bình thường')], max_length=255, null=True)),
                ('do_mat', models.CharField(blank=True, choices=[('Bình thường', 'Bình thường'), ('Mật', 'Mật'), ('Tuyệt Mật', 'Tuyệt Mật')], max_length=255, null=True)),
                ('file_dinh_kem', models.FileField(upload_to='van_ban/')),
                ('kich_thuoc', models.BigIntegerField()),
                ('trang_thai', models.CharField(choices=[('Chờ Xử Lý', 'Chờ Xử Lý'), ('Đã Xử Lý', 'Đã Xử Lý'), ('Hoàn Trả', 'Hoàn Trả'), ('Xem Để Biết', 'Xem Để Biết'), ('Đã ban hành', 'Đã ban hành')], max_length=255)),
                ('noi_dung', models.TextField()),
                ('phan_loai', models.CharField(choices=[('Văn bản đi', 'Văn bản đi'), ('Văn bản đến', 'Văn bản đến')], max_length=255)),
                ('ho_so_van_ban', models.ForeignKey(db_column='ho_so_van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.hosovanban')),
                ('lanh_dao_duyet', models.ForeignKey(db_column='lanh_dao_duyet_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.nguoidung')),
                ('nguoi_tao', models.ForeignKey(db_column='nguoi_tao_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.nguoidung')),
            ],
            options={
                'db_table': 'VanBan',
            },
        ),
        migrations.CreateModel(
            name='VanBanLienQuan',
            fields=[
                ('van_ban_lien_quan_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_van_ban', models.FileField(upload_to='van_ban_lien_quan/')),
                ('kich_thuoc', models.IntegerField()),
                ('van_ban', models.ForeignKey(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban')),
            ],
            options={
                'db_table': 'VanBanLienQuan',
            },
        ),
        migrations.CreateModel(
            name='VanBanHoanTra',
            fields=[
                ('van_ban_hoan_tra_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_hoan_tra', models.DateField(auto_now_add=True)),
                ('noi_dung', models.TextField()),
                ('van_ban', models.ForeignKey(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban')),
            ],
            options={
                'db_table': 'VanBanHoanTra',
            },
        ),
        migrations.CreateModel(
            name='VanBanDuyet',
            fields=[
                ('van_ban_duyet_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_duyet', models.DateField(auto_now_add=True)),
                ('van_ban', models.ForeignKey(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban')),
                ('van_thu', models.ForeignKey(db_column='van_thu_id', on_delete=django.db.models.deletion.CASCADE, to='core.nguoidung')),
            ],
            options={
                'db_table': 'VanBanDuyet',
            },
        ),
        migrations.CreateModel(
            name='PhongXemHoSo',
            fields=[
                ('phong_xem_ho_so_id', models.AutoField(primary_key=True, serialize=False)),
                ('ho_so_van_ban', models.ForeignKey(db_column='ho_so_van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.hosovanban')),
                ('phong_ban', models.ForeignKey(db_column='phong_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.phongban')),
            ],
            options={
                'db_table': 'PhongXemHoSo',
            },
        ),
        migrations.CreateModel(
            name='PheDuyetCongViec',
            fields=[
                ('phe_duyet_cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_duyet', models.DateField(auto_now_add=True)),
                ('cong_viec', models.ForeignKey(db_column='cong_viec_id', on_delete=django.db.models.deletion.CASCADE, to='core.congviec')),
            ],
            options={
                'db_table': 'PheDuyetCongViec',
            },
        ),
        migrations.CreateModel(
            name='PhanCongCongViec',
            fields=[
                ('phan_cong_id', models.AutoField(primary_key=True, serialize=False)),
                ('cong_viec', models.ForeignKey(db_column='cong_viec_id', on_delete=django.db.models.deletion.CASCADE, to='core.congviec')),
                ('nguoi_phoi_hop', models.ForeignKey(db_column='nguoi_phoi_hop_id', on_delete=django.db.models.deletion.CASCADE, to='core.nguoidung')),
            ],
            options={
                'db_table': 'PhanCongCongViec',
            },
        ),
        migrations.CreateModel(
            name='NguoiXuLyHoSo',
            fields=[
                ('nguoi_xu_ly_ho_so_id', models.AutoField(primary_key=True, serialize=False)),
                ('ho_so_van_ban', models.ForeignKey(db_column='ho_so_van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.hosovanban')),
                ('nguoi_xu_ly', models.ForeignKey(db_column='nguoi_xu_ly_id', on_delete=django.db.models.deletion.CASCADE, to='core.nguoidung')),
            ],
            options={
                'db_table': 'NguoiXuLyHoSo',
            },
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='phong_ban',
            field=models.ForeignKey(db_column='phong_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.phongban'),
        ),
        migrations.AddField(
            model_name='hosovanban',
            name='nguoi_tao',
            field=models.ForeignKey(db_column='nguoi_tao_id', on_delete=django.db.models.deletion.CASCADE, to='core.nguoidung'),
        ),
        migrations.CreateModel(
            name='HoanTraCongViec',
            fields=[
                ('hoan_tra_cong_viec_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_hoan_tra', models.DateField(auto_now_add=True)),
                ('noi_dung', models.TextField()),
                ('cong_viec', models.ForeignKey(db_column='cong_viec_id', on_delete=django.db.models.deletion.CASCADE, to='core.congviec')),
            ],
            options={
                'db_table': 'HoanTraCongViec',
            },
        ),
        migrations.CreateModel(
            name='FileCVLienQuan',
            fields=[
                ('file_cv_lien_quan_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_van_ban', models.FileField(upload_to='file_cv_lien_quan/')),
                ('kich_thuoc', models.IntegerField(blank=True, null=True)),
                ('cong_viec', models.ForeignKey(db_column='cong_viec_id', on_delete=django.db.models.deletion.CASCADE, to='core.congviec')),
            ],
            options={
                'db_table': 'FileCVLienQuan',
            },
        ),
        migrations.AddField(
            model_name='congviec',
            name='nguoi_giao',
            field=models.ForeignKey(db_column='nguoi_giao_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.nguoidung'),
        ),
        migrations.AddField(
            model_name='congviec',
            name='nguoi_thuc_hien',
            field=models.ForeignKey(db_column='nguoi_thuc_hien_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.nguoidung'),
        ),
        migrations.AddField(
            model_name='congviec',
            name='van_ban',
            field=models.ForeignKey(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
        migrations.CreateModel(
            name='ChuyenTiepChiTiet',
            fields=[
                ('chuyen_tiep_ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('chuyen_tiep', models.ForeignKey(db_column='chuyen_tiep_id', on_delete=django.db.models.deletion.CASCADE, to='core.chuyentiep')),
                ('nguoi_dung', models.ForeignKey(db_column='nguoi_dung_id', on_delete=django.db.models.deletion.CASCADE, to='core.nguoidung')),
                ('phong_ban', models.ForeignKey(db_column='phong_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.phongban')),
            ],
            options={
                'db_table': 'ChuyenTiepChiTiet',
            },
        ),
        migrations.AddField(
            model_name='chuyentiep',
            name='van_ban_duyet',
            field=models.ForeignKey(db_column='van_ban_duyet_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanbanduyet'),
        ),
        migrations.CreateModel(
            name='BanHanhChiTiep',
            fields=[
                ('ban_hanh_ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('ban_hanh', models.ForeignKey(db_column='ban_hanh_id', on_delete=django.db.models.deletion.CASCADE, to='core.banhanh')),
                ('don_vi_ngoai', models.ForeignKey(db_column='don_vi_ngoai_id', on_delete=django.db.models.deletion.CASCADE, to='core.donvingoai')),
                ('phong_ban', models.ForeignKey(db_column='phong_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.phongban')),
            ],
            options={
                'db_table': 'BanHanhChiTiep',
            },
        ),
        migrations.AddField(
            model_name='banhanh',
            name='van_ban',
            field=models.ForeignKey(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
    ]
