# Generated by Django 6.0.3 on 2026-04-10 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_customers_to_core_users(apps, schema_editor):
    customer_model = apps.get_model("accounts", "Customer")
    nguoi_dung_model = apps.get_model("core", "NguoiDung")

    role_chuc_vu_map = {
        "ADMIN": "Quản Trị Hệ Thống",
        "LANH_DAO": "Lãnh Đạo",
        "VAN_THU": "Văn Thư",
        "CHUYEN_VIEN": "Chuyên Viên",
    }
    valid_chuc_vu_values = set(role_chuc_vu_map.values())

    for customer in customer_model.objects.all():
        core_profile = nguoi_dung_model.objects.filter(tai_khoan_id=customer.pk).first()
        if core_profile is None and customer.email:
            email_match = nguoi_dung_model.objects.filter(email__iexact=customer.email).first()
            if email_match and email_match.tai_khoan_id in (None, customer.pk):
                core_profile = email_match

        if core_profile is None:
            core_profile = nguoi_dung_model()

        normalized_chuc_vu = (customer.chuc_vu or "").strip()
        if normalized_chuc_vu not in valid_chuc_vu_values:
            normalized_chuc_vu = role_chuc_vu_map.get(customer.role, "Chuyên Viên")

        core_profile.tai_khoan_id = customer.pk
        core_profile.ho_va_ten = (customer.ho_va_ten or customer.username or "").strip()
        core_profile.email = customer.email
        core_profile.sdt = customer.sdt
        core_profile.chuc_vu = normalized_chuc_vu
        if customer.phong_ban_id:
            core_profile.phong_ban_id = customer.phong_ban_id
        core_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='tai_khoan',
            field=models.OneToOneField(blank=True, db_column='tai_khoan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_dung_core', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='chuc_vu',
            field=models.CharField(choices=[('Quản Trị Hệ Thống', 'Quản Trị Hệ Thống'), ('Lãnh Đạo', 'Lãnh Đạo'), ('Chuyên Viên', 'Chuyên Viên'), ('Văn Thư', 'Văn Thư')], max_length=255),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='phong_ban',
            field=models.ForeignKey(blank=True, db_column='phong_ban_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phongban'),
        ),
        migrations.RunPython(
            link_existing_customers_to_core_users,
            migrations.RunPython.noop,
        ),
    ]
