# Generated by Django 4.2.8 on 2026-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nguoidung_tai_khoan_alter_nguoidung_chuc_vu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vanban',
            name='don_vi_ban_hanh',
        ),
        migrations.AlterField(
            model_name='vanban',
            name='don_vi_soan_thao',
            field=models.CharField(choices=[('Ban Giám Đốc', 'Ban Giám Đốc'), ('Phòng Kế Toán', 'Phòng Kế Toán'), ('Phòng Kiểm Toán', 'Phòng Kiểm Toán'), ('Phòng Tư Vấn Thuế', 'Phòng Tư Vấn Thuế'), ('Phòng Hành Chính/Nhân sự', 'Phòng Hành Chính/Nhân sự'), ('Phòng Đào Tạo Chất Lượng', 'Phòng Đào Tạo Chất Lượng')], max_length=255),
        ),
    ]
