# Generated by Django 4.2.8 on 2026-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nguoidung_tai_khoan_alter_nguoidung_chuc_vu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosovanban',
            name='thoi_gian_bao_quan',
            field=models.CharField(choices=[('Theo quy định - 2 năm', 'Theo quy định - 2 năm'), ('Theo quy định - 5 năm', 'Theo quy định - 5 năm'), ('Theo quy định - 10 năm', 'Theo quy định - 10 năm'), ('Vĩnh viễn', 'Vĩnh viễn'), ('Tạm thời', 'Tạm thời')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hosovanban',
            name='trang_thai',
            field=models.IntegerField(choices=[(1, 'Hiện hành'), (2, 'Lưu trữ')], default=1),
        ),
        migrations.AlterField(
            model_name='vanban',
            name='don_vi_soan_thao',
            field=models.CharField(choices=[('Ban Giám Đốc', 'Ban Giám Đốc'), ('Phòng Kế Toán', 'Phòng Kế Toán'), ('Phòng Kiểm Toán', 'Phòng Kiểm Toán'), ('Phòng Tư Vấn Thuế', 'Phòng Tư Vấn Thuế'), ('Phòng Hành Chính/Nhân sự', 'Phòng Hành Chính/Nhân sự'), ('Phòng Đào Tạo Chất Lượng', 'Phòng Đào Tạo Chất Lượng')], max_length=255),
        ),
    ]
