# Generated by Django 4.2.8 on 2026-04-11 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nguoidung_tai_khoan_alter_nguoidung_chuc_vu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congviec',
            name='van_ban',
            field=models.ForeignKey(blank=True, db_column='van_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
        migrations.AlterField(
            model_name='vanban',
            name='don_vi_soan_thao',
            field=models.CharField(choices=[('Ban Giám Đốc', 'Ban Giám Đốc'), ('Phòng Kế Toán', 'Phòng Kế Toán'), ('Phòng Kiểm Toán', 'Phòng Kiểm Toán'), ('Phòng Tư Vấn Thuế', 'Phòng Tư Vấn Thuế'), ('Phòng Hành Chính/Nhân sự', 'Phòng Hành Chính/Nhân sự'), ('Phòng Đào Tạo Chất Lượng', 'Phòng Đào Tạo Chất Lượng')], max_length=255),
        ),
    ]
