# Generated by Django 4.2.8 on 2026-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_congviec_van_ban_alter_vanban_don_vi_soan_thao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congviec',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ xử lý', 'Chờ xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Hoàn trả', 'Hoàn trả'), ('Đã hoàn thành', 'Đã hoàn thành')], default='Chờ xử lý', max_length=255),
        ),
    ]
