# Generated by Django 4.2.8 on 2026-04-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hosovanban_thoi_gian_bao_quan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanban',
            name='ho_so_van_ban',
            field=models.ForeignKey(blank=True, db_column='ho_so_van_ban_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hosovanban'),
        ),
    ]
