# Generated by Django 4.2.8 on 2026-04-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_vanban_don_vi_ban_hanh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanban',
            name='ho_so_van_ban',
            field=models.ForeignKey(db_column='ho_so_van_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hosovanban'),
        ),
        migrations.AlterField(
            model_name='vanban',
            name='ngay_den',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vanban',
            name='noi_dung',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vanbanlienquan',
            name='van_ban',
            field=models.ForeignKey(db_column='van_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
    ]
