# Generated by Django 4.2.8 on 2026-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vanban_ho_so_van_ban_alter_vanban_ngay_den_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanban',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ Xử Lý', 'Chờ Xử Lý'), ('Đã Xử Lý', 'Đã Xử Lý'), ('Hoàn Trả', 'Hoàn Trả'), ('Xem Để Biết', 'Xem Để Biết'), ('Chờ ban hành', 'Chờ ban hành'), ('Đã ban hành', 'Đã ban hành')], max_length=255),
        ),
    ]
