# Generated by Django 4.2.8 on 2026-04-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vanban_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banhanhchitiep',
            name='don_vi_ngoai',
            field=models.ForeignKey(blank=True, db_column='don_vi_ngoai_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.donvingoai'),
        ),
        migrations.AlterField(
            model_name='banhanhchitiep',
            name='phong_ban',
            field=models.ForeignKey(blank=True, db_column='phong_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phongban'),
        ),
    ]
