# Generated by Django 4.2.8 on 2026-04-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_congviec_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congviec',
            name='nguon_giao',
            field=models.CharField(blank=True, choices=[('Văn bản đến', 'Văn bản đến'), ('Văn bản đi', 'Văn bản đi')], max_length=255, null=True),
        ),
    ]
