# Generated by Django 4.2.8 on 2026-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_congviec_nguon_giao'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecvlienquan',
            name='loai_file',
            field=models.CharField(choices=[('CHINH', 'Chính'), ('LIEN_QUAN', 'Liên quan')], default='LIEN_QUAN', max_length=20),
        ),
    ]
