# Generated by Django 4.2.8 on 2026-04-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_filecvlienquan_loai_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='congviec',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
