# Generated by Django 4.2.8 on 2026-04-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_congviec_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='congviec',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
