# Generated by Django 4.2.8 on 2026-04-14 12:00

from django.db import migrations, models
import django.db.models.deletion


OLD_RETURN_STATUS = "Hoàn trả"
RETURN_TO_SPECIALIST = "Hoàn trả_CV"
RETURN_TO_LEADER = "Hoàn trả_LĐ"


def forwards(apps, schema_editor):
    CongViec = apps.get_model("core", "CongViec")
    FileCVLienQuan = apps.get_model("core", "FileCVLienQuan")
    HoanTraCongViec = apps.get_model("core", "HoanTraCongViec")

    task_map = {task.pk: task for task in CongViec.objects.all()}

    for task in task_map.values():
        has_result = bool((task.ket_qua_xu_ly or "").strip())
        if task.trang_thai == OLD_RETURN_STATUS:
            task.trang_thai = RETURN_TO_SPECIALIST if has_result else RETURN_TO_LEADER
            task.save(update_fields=["trang_thai"])

    for attachment in FileCVLienQuan.objects.all():
        task = task_map.get(attachment.cong_viec_id)
        if not task:
            continue
        attachment.nguon_tai_len = "GIAO_VIEC"
        attachment.nguoi_tai_len_id = task.nguoi_giao_id
        attachment.save(update_fields=["nguon_tai_len", "nguoi_tai_len"])

    for history in HoanTraCongViec.objects.all():
        task = task_map.get(history.cong_viec_id)
        if not task:
            continue
        has_result = bool((task.ket_qua_xu_ly or "").strip())
        history.nguoi_hoan_tra_id = task.nguoi_giao_id if has_result else task.nguoi_thuc_hien_id
        history.save(update_fields=["nguoi_hoan_tra"])


def backwards(apps, schema_editor):
    CongViec = apps.get_model("core", "CongViec")
    CongViec.objects.filter(trang_thai__in=[RETURN_TO_SPECIALIST, RETURN_TO_LEADER]).update(
        trang_thai=OLD_RETURN_STATUS
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_congviec_ghi_chu"),
    ]

    operations = [
        migrations.AddField(
            model_name="congviec",
            name="yeu_cau_phe_duyet",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="filecvlienquan",
            name="nguoi_tai_len",
            field=models.ForeignKey(
                blank=True,
                db_column="nguoi_tai_len_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.nguoidung",
            ),
        ),
        migrations.AddField(
            model_name="filecvlienquan",
            name="nguon_tai_len",
            field=models.CharField(
                choices=[
                    ("GIAO_VIEC", "File giao việc"),
                    ("KET_QUA_XU_LY", "File kết quả xử lý"),
                ],
                default="GIAO_VIEC",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="hoantracongviec",
            name="nguoi_hoan_tra",
            field=models.ForeignKey(
                blank=True,
                db_column="nguoi_hoan_tra_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.nguoidung",
            ),
        ),
        migrations.AlterField(
            model_name="congviec",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("Chờ xử lý", "Chờ xử lý"),
                    ("Đã hoàn thành", "Đã hoàn thành"),
                    ("Hoàn trả_CV", "Hoàn trả CV"),
                    ("Hoàn trả_LĐ", "Hoàn trả LĐ"),
                    ("Chờ duyệt", "Chờ duyệt"),
                ],
                default="Chờ xử lý",
                max_length=255,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
