# Generated by Django 4.2.8 on 2026-04-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_vanban_ho_so_van_ban'),
        ('core', '0006_alter_banhanhchitiep_don_vi_ngoai_and_more'),
        ('core', '0011_congviec_workflow_fields'),
    ]

    operations = [
    ]
