# Generated by Django 6.0.3 on 2026-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260414_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanban',
            name='ngay_van_ban',
            field=models.DateField(),
        ),
    ]
