# Generated by Django 4.2.8 on 2026-04-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanbanden', '0001_initial'),
        ('core', '0013_alter_vanban_ngay_van_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='congviec',
            name='van_ban_den',
            field=models.ForeignKey(blank=True, db_column='van_ban_den_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quanlyvanbanden.vanbanden'),
        ),
        migrations.AlterField(
            model_name='congviec',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ xử lý', 'Chờ xử lý'), ('Đã hoàn thành', 'Đã hoàn thành'), ('Hoàn trả_CV', 'Hoàn trả'), ('Hoàn trả_LĐ', 'Hoàn trả'), ('Chờ duyệt', 'Chờ duyệt')], default='Chờ xử lý', max_length=255),
        ),
        migrations.AlterField(
            model_name='congviec',
            name='van_ban',
            field=models.ForeignKey(blank=True, db_column='van_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.vanban'),
        ),
    ]
