# Generated by Django 4.2.8 on 2026-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_vanban_ngay_van_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanban',
            name='don_vi_ban_hanh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
