# Generated by Django 4.2.8 on 2026-04-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_congviec_van_ban_den_alter_congviec_trang_thai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congviec',
            name='van_ban_den',
        ),
        migrations.AlterField(
            model_name='congviec',
            name='van_ban',
            field=models.ForeignKey(blank=True, db_column='van_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
    ]
