# Generated by Django 4.2.8 on 2026-04-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlyvanbanden', '0001_initial'),
        ('core', '0015_remove_congviec_van_ban_den_alter_congviec_van_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='congviec',
            name='van_ban_den',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cong_viec_lien_quan', to='quanlyvanbanden.vanbanden'),
        ),
    ]
