# Generated by Django 4.2.8 on 2026-04-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_congviec_van_ban_den'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiNhanVanBan',
            fields=[
                ('noi_nhan_id', models.AutoField(primary_key=True, serialize=False)),
                ('don_vi_ngoai', models.ForeignKey(blank=True, db_column='don_vi_ngoai_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.donvingoai')),
                ('phong_ban', models.ForeignKey(blank=True, db_column='phong_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phongban')),
            ],
            options={
                'db_table': 'NoiNhanVanBan',
            },
        ),
        migrations.RemoveField(
            model_name='vanban',
            name='don_vi_soan_thao',
        ),
        migrations.AlterField(
            model_name='banhanh',
            name='van_ban',
            field=models.OneToOneField(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
        migrations.AlterField(
            model_name='vanbanduyet',
            name='van_ban',
            field=models.OneToOneField(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
        migrations.DeleteModel(
            name='BanHanhChiTiep',
        ),
        migrations.AddField(
            model_name='noinhanvanban',
            name='van_ban',
            field=models.ForeignKey(db_column='van_ban_id', on_delete=django.db.models.deletion.CASCADE, to='core.vanban'),
        ),
    ]
