# Generated by Django 4.2.8 on 2026-04-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_noinhanvanban_remove_vanban_don_vi_soan_thao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChuKySo',
            fields=[
                ('chu_ky_so_id', models.AutoField(primary_key=True, serialize=False)),
                ('anh_chu_ky', models.ImageField(blank=True, null=True, upload_to='anh_chu_ky/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nguoi_dung', models.OneToOneField(db_column='nguoi_dung_id', on_delete=django.db.models.deletion.CASCADE, related_name='chu_ky_so', to='core.nguoidung')),
            ],
            options={
                'db_table': 'ChuKySo',
            },
        ),
        migrations.CreateModel(
            name='LichSuKySo',
            fields=[
                ('lich_su_ky_so_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_tai_lieu', models.CharField(max_length=255)),
                ('file_da_ky', models.FileField(blank=True, null=True, upload_to='file_da_ky/')),
                ('thoi_gian_ky', models.DateTimeField(auto_now_add=True)),
                ('chu_ky_so', models.ForeignKey(db_column='chu_ky_so_id', on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_ky_so', to='core.chukyso')),
                ('cong_viec', models.OneToOneField(blank=True, db_column='cong_viec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_ky_so', to='core.congviec')),
                ('van_ban', models.OneToOneField(blank=True, db_column='van_ban_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_ky_so', to='core.vanban')),
            ],
            options={
                'db_table': 'LichSuKySo',
            },
        ),
        migrations.CreateModel(
            name='LichSuHoatDong',
            fields=[
                ('lich_su_id', models.AutoField(primary_key=True, serialize=False)),
                ('doi_tuong_loai', models.CharField(choices=[('VAN_BAN', 'Văn bản'), ('CONG_VIEC', 'Công việc'), ('HO_SO', 'Hồ sơ văn bản')], max_length=50)),
                ('doi_tuong_id', models.PositiveIntegerField()),
                ('hanh_dong', models.CharField(choices=[('TAO', 'Tạo'), ('SUA', 'Sửa'), ('XOA', 'Xóa'), ('DUYET', 'Duyệt'), ('HOAN_TRA', 'Hoàn trả'), ('CHUYEN_TIEP', 'Chuyển tiếp'), ('BAN_HANH', 'Ban hành'), ('KY_SO', 'Ký số')], max_length=50)),
                ('truoc_thay_doi', models.JSONField(blank=True, null=True)),
                ('sau_thay_doi', models.JSONField(blank=True, null=True)),
                ('thoi_gian_thuc_hien', models.DateTimeField(auto_now_add=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('nguoi_thuc_hien', models.ForeignKey(blank=True, db_column='nguoi_thuc_hien_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_su_hoat_dong', to='core.nguoidung')),
            ],
            options={
                'db_table': 'LichSuHoatDong',
            },
        ),
        migrations.AddConstraint(
            model_name='lichsukyso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('van_ban__isnull', False), ('cong_viec__isnull', True)), models.Q(('van_ban__isnull', True), ('cong_viec__isnull', False)), _connector='OR'), name='ck_lich_su_ky_so_chi_mot_doi_tuong'),
        ),
        migrations.AddIndex(
            model_name='lichsuhoatdong',
            index=models.Index(fields=['doi_tuong_loai', 'doi_tuong_id'], name='LichSuHoatD_doi_tuo_4a1e88_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsuhoatdong',
            index=models.Index(fields=['hanh_dong'], name='LichSuHoatD_hanh_do_e2fbf4_idx'),
        ),
        migrations.AddIndex(
            model_name='lichsuhoatdong',
            index=models.Index(fields=['thoi_gian_thuc_hien'], name='LichSuHoatD_thoi_gi_8f96c1_idx'),
        ),
    ]
