# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_chukyso_lichsukyso_lichsuhoatdong_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lichsukyso",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="lichsukyso",
            name="hash_algorithm",
            field=models.CharField(default="SHA-256", max_length=20),
        ),
        migrations.AddField(
            model_name="lichsukyso",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="chu_ky_so/"),
        ),
        migrations.AddField(
            model_name="lichsukyso",
            name="verified",
            field=models.BooleanField(default=True),
        ),
    ]
