# Generated by Django 6.0.3 on 2026-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_lichsukyso_sha256_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanbanduyet',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vanbanhoantra',
            name='han_xu_ly_hoan_tra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
