# Generated by Django 6.0.3 on 2026-04-14 12:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VanBanDen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_ky_hieu', models.CharField(max_length=100, unique=True)),
                ('don_vi_ban_hanh', models.CharField(max_length=255)),
                ('trich_yeu', models.CharField(max_length=500)),
                ('loai_van_ban', models.CharField(choices=[('HANH_CHINH', 'Hành chính'), ('QUYET_DINH', 'Quyết định'), ('CONG_VAN', 'Công văn'), ('THONG_TU', 'Thông tư'), ('THONG_BAO', 'Thông báo'), ('BAO_CAO', 'Báo cáo'), ('KE_HOACH', 'Kế hoạch')], default='HANH_CHINH', max_length=50)),
                ('hinh_thuc_van_ban', models.CharField(choices=[('CONG_VAN', 'Công văn'), ('QUYET_DINH', 'Quyết định'), ('THONG_TU', 'Thông tư'), ('THONG_BAO', 'Thông báo'), ('TO_TRINH', 'Tờ trình')], default='CONG_VAN', max_length=30)),
                ('ngay_van_ban', models.DateField()),
                ('ngay_den', models.DateField(default=django.utils.timezone.now)),
                ('han_xu_ly', models.DateField(blank=True, null=True)),
                ('do_mat', models.CharField(choices=[('BINH_THUONG', 'Bình thường'), ('MAT', 'Mật'), ('TOI_MAT', 'Tối mật')], default='BINH_THUONG', max_length=20)),
                ('do_khan', models.CharField(choices=[('BINH_THUONG', 'Bình thường'), ('KHAN', 'Khẩn'), ('HOA_TOC', 'Hỏa tốc')], default='BINH_THUONG', max_length=20)),
                ('linh_vuc', models.CharField(blank=True, max_length=255, null=True)),
                ('noi_dung_xu_ly', models.TextField(blank=True)),
                ('ly_do_hoan_tra', models.TextField(blank=True)),
                ('ngay_hoan_tra', models.DateField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('CHO_XU_LY', 'Chờ xử lý'), ('DA_XU_LY', 'Đã xử lý'), ('HOAN_TRA', 'Hoàn trả'), ('XEM_DE_BIET', 'Xem để biết')], default='CHO_XU_LY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lanh_dao_xu_ly', models.ForeignKey(limit_choices_to={'role': 'LANH_DAO'}, on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_den_duoc_giao', to=settings.AUTH_USER_MODEL)),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_den_da_tao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TepVanBanDen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('DINH_KEM', 'File đính kèm'), ('LIEN_QUAN', 'Tài liệu liên quan')], max_length=20)),
                ('tep', models.FileField(upload_to='van_ban_den/tep_tin/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'png', 'jpg', 'jpeg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('van_ban_den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tep_tin', to='quanlyvanbanden.vanbanden')),
            ],
        ),
        migrations.CreateModel(
            name='VanBanDenChuyenTiep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chuyen_vien', models.ForeignKey(limit_choices_to={'role': 'CHUYEN_VIEN'}, on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_den_duoc_chuyen_tiep', to=settings.AUTH_USER_MODEL)),
                ('nguoi_chuyen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='van_ban_den_da_chuyen_tiep', to=settings.AUTH_USER_MODEL)),
                ('van_ban_den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_chuyen_tiep', to='quanlyvanbanden.vanbanden')),
            ],
            options={
                'unique_together': {('van_ban_den', 'chuyen_vien')},
            },
        ),
    ]
