# Generated by Django 4.2.8 on 2026-04-02 13:46

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ho_va_ten', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('chuc_vu', models.CharField(blank=True, max_length=255, verbose_name='Chức vụ')),
                ('sdt', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('role', models.CharField(choices=[('ADMIN', 'Quản trị hệ thống'), ('LANH_DAO', 'Lãnh đạo'), ('VAN_THU', 'Văn thư'), ('CHUYEN_VIEN', 'Chuyên viên')], default='CHUYEN_VIEN', max_length=20, verbose_name='Vai trò')),
                ('chi_nhanh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.chinhanh', verbose_name='Chi nhánh')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('phong_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.phongban', verbose_name='Phòng ban')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'permissions': [('access_admin_area', 'Có thể vào khu vực quản trị hệ thống'), ('access_lanh_dao_area', 'Có thể vào khu vực lãnh đạo'), ('access_van_thu_area', 'Có thể vào khu vực văn thư'), ('access_chuyen_vien_area', 'Có thể vào khu vực chuyên viên'), ('manage_users', 'Có thể quản lý người dùng'), ('manage_departments', 'Có thể quản lý chi nhánh và phòng ban'), ('view_reports', 'Có thể xem báo cáo thống kê'), ('present_incoming_document', 'Có thể trình văn bản đến'), ('edit_incoming_document', 'Có thể chỉnh sửa văn bản đến'), ('delete_incoming_document', 'Có thể xóa văn bản đến'), ('return_incoming_document', 'Có thể hoàn trả văn bản đến'), ('forward_document', 'Có thể chuyển tiếp văn bản'), ('draft_outgoing_document', 'Có thể soạn thảo văn bản đi'), ('edit_outgoing_document', 'Có thể chỉnh sửa văn bản đi'), ('delete_outgoing_document', 'Có thể xóa văn bản đi'), ('approve_outgoing_document', 'Có thể phê duyệt văn bản đi'), ('return_outgoing_document', 'Có thể hoàn trả văn bản đi'), ('issue_outgoing_document', 'Có thể ban hành văn bản đi'), ('assign_task', 'Có thể giao việc'), ('edit_task', 'Có thể chỉnh sửa công việc'), ('delete_task', 'Có thể xóa công việc'), ('approve_task', 'Có thể duyệt công việc'), ('return_task', 'Có thể hoàn trả công việc'), ('process_task', 'Có thể xử lý công việc'), ('update_task_result', 'Có thể cập nhật xử lý công việc'), ('manage_records', 'Có thể quản lý hồ sơ văn bản'), ('add_document_to_record', 'Có thể thêm văn bản vào hồ sơ'), ('remove_document_from_record', 'Có thể xóa văn bản khỏi hồ sơ')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
